// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import PublishedController from "./published_controller"
application.register("published", PublishedController)

import RelativeController from "./relative_controller"
application.register("relative", RelativeController)

