services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    image: mini-devto:1.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:changeme@db
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/usr/src/app/.dockerdev/.bash_history
      - MALLOC_ARENA_MAX=2
    volumes:
      - .:/usr/src/app/:cached
      - bundle:/usr/local/bundle
      - rails_cache:/usr/src/app/tmp/cache
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
      - redis
  webpack:
    build: .
    image: mini-devto:1.0
    command: yarn build --watch
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  bundle:
  db_data:
  node_modules:
  rails_cache:
  redis_data: